package sandbox

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/kuasar-sandbox/accelerator/pkg/manifest"
	"github.com/kuasar-sandbox/accelerator/pkg/manifest/chunker"
	manifestcrypto "github.com/kuasar-sandbox/accelerator/pkg/manifest/crypto"
	"github.com/kuasar-sandbox/accelerator/pkg/manifest/fetch"
	"github.com/kuasar-sandbox/accelerator/pkg/sparse"
	"github.com/kuasar-sandbox/accelerator/pkg/store"
	"github.com/kuasar-sandbox/sandboxer/pkg/artifact"
	"github.com/kuasar-sandbox/sandboxer/pkg/config"
	"github.com/kuasar-sandbox/sandboxer/pkg/snapshot"
	"github.com/kuasar-sandbox/sandboxer/pkg/snapshotfile"
)

func TestCheckpointMemoryHistoryRoundsAndSwitches(t *testing.T) {
	for _, carrier := range []string{"local", "bundle", "mixed"} {
		t.Run(carrier, func(t *testing.T) {
			ctx := context.Background()
			dir := t.TempDir()
			key := [32]byte{7}
			cfg := &config.ManifestConfig{Manifest: manifest.ManifestSubConfig{Key: fmt.Sprintf("%x", key), WriteGeneration: "G1"},
				Chunker: chunker.Config{Mode: "fixed", Fixed: chunker.FixedConfig{Size: "4KiB"}}, Crypto: manifestcrypto.Config{Chunk: "aes", Manifest: "aes", Local: manifestcrypto.LocalOff}}
			keyFn := func() ([32]byte, error) { return key, nil }
			remote := &checkpointNoFetch{t: t}
			opts := RunOptions{checkpointDir: dir, ManifestCfg: cfg, CustomerKeyFn: keyFn, Fetcher: remote}
			external := []string{"manifest://" + strings.Repeat("e", 64), "file://external.snapshot@location:template@digest:" + strings.Repeat("f", 64)}
			// Use a syntactically valid located ref generated by the parser's own type.
			external[1] = (manifest.Ref{Scheme: manifest.RefSchemeFile, Path: "external.snapshot", Location: "template", DigestScheme: "digest", Digest: strings.Repeat("f", 64)}).String()
			var old *artifact.OpenedFile
			defer func() {
				if old != nil {
					_ = old.Close()
				}
			}()
			expected := make([]byte, 4*4096)
			for round, merge := range []bool{false, false, false, false, true, false, false, true, false} {
				history, err := prepareMemoryHistory(ctx, opts, merge, uint64(len(expected)))
				if err != nil {
					t.Fatalf("round %d prepare: %v", round, err)
				}
				var sink snapshot.ArtifactSink
				bundleMode := carrier == "bundle" || carrier == "mixed" && round%2 == 1
				if bundleMode {
					sink, err = snapshot.NewBundleSink(ctx, dir, "sid", cfg, keyFn, nil)
					if err != nil {
						t.Fatal(err)
					}
				} else {
					sink = snapshot.NewFileSink(dir, "sid", nil, false, nil)
				}
				refs := append([]string(nil), history.refs...)
				if round == 0 {
					refs = append([]string(nil), external...)
				}
				if history.historical != nil {
					ref, _, err := sink.AbsorbSnapshot(ctx, history.historical)
					if err != nil {
						t.Fatal(err)
					}
					refs = append([]string{ref}, refs...)
				}
				// In actual capture the dependency plan materializes unlocated Bundle
				// members when crossing carriers. Exercise that same production helper.
				if history.historical == nil && len(refs) > len(external) {
					dep := artifactDependency{raw: refs[0], role: dependencyMemorySnapshot}
					stream, _, _, _, err := openSnapshotDependency(ctx, dep, opts, bundleKnownRefPaths(opts), dir)
					if err != nil {
						t.Fatal(err)
					}
					ref, _, err := sink.AbsorbSnapshot(ctx, stream)
					closeErr := stream.Close()
					if err != nil || closeErr != nil {
						t.Fatal(err, closeErr)
					}
					refs[0] = ref
				}
				body := make([]byte, len(expected))
				page := round % 4
				if round == 2 {
					page = 0
				}
				for i := page * 4096; i < (page+1)*4096; i++ {
					body[i] = byte(round + 1)
					if round == 2 {
						body[i] = 0
					}
					expected[i] = body[i]
				}
				var holes []sparse.Extent
				if page > 0 {
					holes = append(holes, sparse.Extent{Offset: 0, Size: uint64(page * 4096)})
				}
				if page < 3 {
					holes = append(holes, sparse.Extent{Offset: uint64((page + 1) * 4096), Size: uint64((3 - page) * 4096)})
				}
				top, err := sparse.NewSource(bytes.NewReader(body), uint64(len(body)), holes)
				if err != nil {
					t.Fatal(err)
				}
				var memory sparse.Source = top
				if history.base != "" {
					memory = fetch.NewLayered(&lifecycleArtifactStream{Source: top}, history.memory)
				}
				sc, err := snapshot.MarshalConfig(&snapshot.Config{Version: snapshot.SnapshotConfigVersion, SandboxRef: "manifest://" + strings.Repeat("a", 64), FromRefs: refs})
				if err != nil {
					t.Fatal(err)
				}
				source, err := snapshotfile.BuildSource(memory, []byte(fmt.Sprintf(`{"round":%d}`, round)), []byte(fmt.Sprintf(`{"cpu":%d}`, round)), sc)
				if err != nil {
					t.Fatal(err)
				}
				ref, path, err := sink.AbsorbSnapshot(ctx, source)
				if err != nil {
					t.Fatal(err)
				}
				if err := sink.CommitSnapshot(ctx, ref, path); err != nil {
					t.Fatal(err)
				}
				if err := sink.Close(); err != nil {
					t.Fatal(err)
				}
				if err := history.Close(); err != nil {
					t.Fatal(err)
				}
				if old != nil {
					if err := old.Close(); err != nil {
						t.Fatal(err)
					}
				}
				runtime := ref
				if bundleMode {
					r, _ := manifest.ParseRef(ref)
					path = filepath.Join(dir, r.Path+".bundle")
					runtime = (manifest.Ref{Scheme: manifest.RefSchemeFile, Path: path, DigestScheme: "manifest", Digest: r.Path}).String()
				} else {
					r, _ := manifest.ParseRef(ref)
					r.Path = path
					runtime = r.String()
				}
				r, _ := manifest.ParseRef(runtime)
				old, err = artifact.OpenFileWithLocations(ctx, path, r, cfg, keyFn, remote, nil, nil, false)
				if err != nil {
					t.Fatal(err)
				}
				root, err := snapshotfile.Open(ctx, old)
				if err != nil {
					t.Fatal(err)
				}
				// The next restore uses only newest S's execution state and E selection.
				if string(root.StateJSON) != fmt.Sprintf(`{"cpu":%d}`, round) {
					t.Fatalf("wrong execution tail: %s", root.StateJSON)
				}
				parsed, err := snapshot.ParseConfig(root.SnapshotConfig)
				if err != nil {
					t.Fatal(err)
				}
				localCount := len(parsed.FromRefs) - len(external)
				want := 0
				if round > 0 && !merge {
					want = 1
				}
				if localCount != want {
					t.Fatalf("round %d lower count %d, want %d: %v", round, localCount, want, parsed.FromRefs)
				}
				if !reflect.DeepEqual(parsed.FromRefs[localCount:], external) {
					t.Fatalf("external order changed: %v", parsed.FromRefs)
				}
				opts.MemoryBinding = &MemorySourceBinding{SnapshotRef: ref, RuntimeRef: runtime, RelativeDir: dir, FromRefs: parsed.FromRefs}
				if bundleMode {
					opts.MemoryBinding.BundleSource = &BundleSourceBinding{RootRef: runtime, RootPath: path, Reader: old.BundleReader(), Fetcher: old.ManifestFetcher()}
				}
				// Compare only the local prefix: external fallback is deliberately never
				// fetched while coalescing historical resident pages.
				all := prependRef(ref, parsed.FromRefs)
				prefix, err := checkpointPrefix(ctx, all, runtime, dir, opts, true)
				if err != nil {
					t.Fatal(err)
				}
				layers := []fetch.Stream{}
				for _, raw := range prefix {
					stream, err := newMemoryMergeBaseOpener(opts)(ctx, raw)
					if err != nil {
						t.Fatal(err)
					}
					layers = append(layers, stream)
				}
				merged := fetch.NewLayered(layers...)
				got := make([]byte, len(expected))
				if n, err := merged.ReadAt(ctx, got, 0); err != nil && err != io.EOF || n != len(got) {
					t.Fatalf("read memory %d: %v", n, err)
				}
				if !bytes.Equal(got, expected) {
					t.Fatalf("round %d memory composition changed", round)
				}
				if err := merged.Close(); err != nil {
					t.Fatal(err)
				}
			}
		})
	}
}

func TestCheckpointPrefixStopsAtExternalOwnership(t *testing.T) {
	dir := t.TempDir()
	external := t.TempDir()
	write := func(where string, value byte) string {
		sink := snapshot.NewFileSink(where, "sid", nil, false, nil)
		cfg, _ := snapshot.MarshalConfig(&snapshot.Config{Version: snapshot.SnapshotConfigVersion, SandboxRef: "manifest://" + strings.Repeat("a", 64)})
		ref, _, err := sink.AbsorbSnapshot(context.Background(), lifecycleSnapshotSource(t, bytes.Repeat([]byte{value}, 4096), cfg))
		if err != nil {
			t.Fatal(err)
		}
		return ref
	}
	local := write(dir, 1)
	other := write(external, 2)
	externalRef, _ := manifest.ParseRef(other)
	externalRef.Path = filepath.Join(external, externalRef.Path)
	opts := RunOptions{checkpointDir: dir}
	prefix, err := checkpointPrefix(context.Background(), []string{local, externalRef.String(), local}, "", dir, opts, true)
	if err != nil || len(prefix) != 1 {
		t.Fatalf("external path boundary: %v %v", prefix, err)
	}
	located, _ := manifest.ParseRef(local)
	located.Location = "template"
	opts.RefLocations = config.RefLocations{"template": dir}
	prefix, err = checkpointPrefix(context.Background(), []string{located.String(), local}, local, dir, opts, true)
	if err != nil || len(prefix) != 0 {
		t.Fatalf("same-path template ownership merged: %v %v", prefix, err)
	}
}

type checkpointNoFetch struct{ t *testing.T }

func (f *checkpointNoFetch) OpenManifest(context.Context, store.ContentKey) (fetch.Stream, error) {
	f.t.Error("history fetched external boundary")
	return nil, fmt.Errorf("unexpected remote open")
}

func TestCheckpointDisksMergeContiguousPrefixAndPreserveEROFS(t *testing.T) {
	ctx := context.Background()
	dir := t.TempDir()
	sink := snapshot.NewFileSink(dir, "sid", nil, false, nil)
	size := int64(4 * 4096)
	writeLayer := func(value byte, page int) string {
		body := bytes.Repeat([]byte{value}, int(size))
		holes := []sparse.Extent{}
		if page > 0 {
			holes = append(holes, sparse.Extent{Offset: 0, Size: uint64(page * 4096)})
		}
		if page < 3 {
			holes = append(holes, sparse.Extent{Offset: uint64((page + 1) * 4096), Size: uint64((3 - page) * 4096)})
		}
		ref, _, err := sink.AbsorbOverlay(ctx, bytes.NewReader(body), holes)
		if err != nil {
			t.Fatal(err)
		}
		return ref
	}
	old := writeLayer(1, 0)
	middle := writeLayer(2, 1)
	top := writeLayer(0, 0) // opaque zero replaces old data
	external := "manifest://" + strings.Repeat("e", 64)
	c0 := snapshotTestLivePortable(t)
	c0.Boot.Root.BaseFromRefs = []string{middle, old, external}
	opts := RunOptions{checkpointDir: dir, Cfg: &config.SandboxConfig{}, PortableConfig: c0,
		SourceBinding: &RunSourceBinding{SandboxRef: top, RuntimeRef: top, RelativeDir: dir}}
	views := 0
	disk := SnapDiskRef{Size: size, SnapshotView: func() (io.ReadSeeker, []sparse.Extent, error) {
		views++
		return bytes.NewReader(make([]byte, size)), nil, nil
	}}
	prepared, diffs, merged, open, err := prepareCheckpointDisks(ctx, opts, []SnapDiskRef{disk})
	if err != nil {
		t.Fatal(err)
	}
	if views != 0 {
		t.Fatal("preflight read guest writable state")
	}
	if !merged[0] || !reflect.DeepEqual(prepared.PortableConfig.Boot.Root.BaseFromRefs, []string{external}) {
		t.Fatalf("disk prefix did not converge: %v %+v", merged, prepared.PortableConfig.Boot.Root)
	}
	stream, err := open(ctx, diffs[0].MergeBase)
	if err != nil {
		t.Fatal(err)
	}
	defer stream.Close()
	got := make([]byte, size)
	if _, err := stream.ReadAt(ctx, got, 0); err != nil {
		t.Fatal(err)
	}
	want := make([]byte, size)
	copy(want[4096:8192], bytes.Repeat([]byte{2}, 4096))
	if !bytes.Equal(got, want) {
		t.Fatal("disk Data/Hole/Zero overlay differs")
	}
	run, err := stream.RunAt(8192, 4096)
	if err != nil || run.Kind() != sparse.Hole {
		t.Fatalf("disk lower fallthrough lost: %v %v", run, err)
	}
	if !reflect.DeepEqual(c0.Boot.Root.BaseFromRefs, []string{middle, old, external}) {
		t.Fatal("immutable C0 mutated")
	}
	// A direct EROFS self is not the ext4 upper's same-device parent.
	opts.PortableConfig = snapshotTestPortable(t)
	opts.PortableConfig.Boot.Root = config.PortableRootConfig{Base: "self", Overlay: &config.PortableOverlayConfig{}}
	prepared, diffs, merged, _, err = prepareCheckpointDisks(ctx, opts, []SnapDiskRef{disk})
	if err != nil || merged[0] || diffs[0].MergeBase != "" {
		t.Fatalf("EROFS merged into upper: %v %v", merged, err)
	}
	if prepared.PortableConfig.Boot.Root.Base != "self" || prepared.PortableConfig.Boot.Root.Overlay == nil {
		t.Fatal("immutable base separation changed")
	}
	// Same-path located template source remains an external owner.
	located, _ := manifest.ParseRef(top)
	located.Location = "template"
	opts.PortableConfig = c0
	opts.RefLocations = config.RefLocations{"template": dir}
	opts.SourceBinding.SandboxRef = located.String()
	_, _, merged, _, err = prepareCheckpointDisks(ctx, opts, []SnapDiskRef{disk})
	if err != nil || merged[0] {
		t.Fatalf("located disk parent absorbed: %v %v", merged, err)
	}
}
