package sandbox

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/kuasar-sandbox/accelerator/pkg/manifest"
	"github.com/kuasar-sandbox/accelerator/pkg/manifest/chunker"
	manifestcrypto "github.com/kuasar-sandbox/accelerator/pkg/manifest/crypto"
	"github.com/kuasar-sandbox/accelerator/pkg/manifest/fetch"
	"github.com/kuasar-sandbox/accelerator/pkg/readerr"
	"github.com/kuasar-sandbox/accelerator/pkg/sparse"
	"github.com/kuasar-sandbox/accelerator/pkg/store"
	"github.com/kuasar-sandbox/sandboxer/pkg/artifact"
	"github.com/kuasar-sandbox/sandboxer/pkg/config"
	"github.com/kuasar-sandbox/sandboxer/pkg/snapshot"
	"github.com/kuasar-sandbox/sandboxer/pkg/snapshotfile"
)

func TestCheckpointMemoryHistoryRoundsAndSwitches(t *testing.T) {
	for _, carrier := range []string{"local", "bundle", "mixed"} {
		t.Run(carrier, func(t *testing.T) {
			ctx := context.Background()
			dir := t.TempDir()
			key := [32]byte{7}
			cfg := &config.ManifestConfig{Manifest: manifest.ManifestSubConfig{Key: fmt.Sprintf("%x", key), WriteGeneration: "G1"},
				Chunker: chunker.Config{Mode: "fixed", Fixed: chunker.FixedConfig{Size: "4KiB"}}, Crypto: manifestcrypto.Config{Chunk: "aes", Manifest: "aes", Local: manifestcrypto.LocalOff}}
			keyFn := func() ([32]byte, error) { return key, nil }
			remote := &checkpointNoFetch{t: t}
			opts := RunOptions{checkpointDir: dir, ManifestCfg: cfg, CustomerKeyFn: keyFn, Fetcher: remote}
			external := []string{"manifest://" + strings.Repeat("e", 64), "file://external.snapshot@location:template@digest:" + strings.Repeat("f", 64)}
			// Use a syntactically valid located ref generated by the parser's own type.
			external[1] = (manifest.Ref{Scheme: manifest.RefSchemeFile, Path: "external.snapshot", Location: "template", DigestScheme: "digest", Digest: strings.Repeat("f", 64)}).String()
			var old *artifact.OpenedFile
			defer func() {
				if old != nil {
					_ = old.Close()
				}
			}()
			expected := make([]byte, 4*4096)
			for round, merge := range []bool{false, false, false, false, true, false, false, true, false} {
				history, err := prepareMemoryHistory(ctx, opts, merge, uint64(len(expected)))
				if err != nil {
					t.Fatalf("round %d prepare: %v", round, err)
				}
				var sink snapshot.ArtifactSink
				bundleMode := carrier == "bundle" || carrier == "mixed" && round%2 == 1
				if bundleMode {
					sink, err = snapshot.NewBundleSink(ctx, dir, "sid", cfg, keyFn, nil)
					if err != nil {
						t.Fatal(err)
					}
				} else {
					sink = snapshot.NewFileSink(dir, "sid", nil, false, nil)
				}
				refs := append([]string(nil), history.refs...)
				if round == 0 {
					refs = append([]string(nil), external...)
				}
				if history.historical != nil {
					ref, _, err := sink.AbsorbSnapshot(ctx, history.historical)
					if err != nil {
						t.Fatal(err)
					}
					refs = append([]string{ref}, refs...)
				}
				// In actual capture the dependency plan materializes unlocated Bundle
				// members when crossing carriers. Exercise that same production helper.
				if history.historical == nil && len(refs) > len(external) {
					dep := artifactDependency{raw: refs[0], role: dependencyMemorySnapshot}
					stream, _, _, _, err := openSnapshotDependency(ctx, dep, opts, bundleKnownRefPaths(opts), dir)
					if err != nil {
						t.Fatal(err)
					}
					ref, _, err := sink.AbsorbSnapshot(ctx, stream)
					closeErr := stream.Close()
					if err != nil || closeErr != nil {
						t.Fatal(err, closeErr)
					}
					refs[0] = ref
				}
				body := make([]byte, len(expected))
				page := round % 4
				if round == 2 {
					page = 0
				}
				for i := page * 4096; i < (page+1)*4096; i++ {
					body[i] = byte(round + 1)
					if round == 2 {
						body[i] = 0
					}
					expected[i] = body[i]
				}
				var holes []sparse.Extent
				if page > 0 {
					holes = append(holes, sparse.Extent{Offset: 0, Size: uint64(page * 4096)})
				}
				if page < 3 {
					holes = append(holes, sparse.Extent{Offset: uint64((page + 1) * 4096), Size: uint64((3 - page) * 4096)})
				}
				top, err := sparse.NewSource(bytes.NewReader(body), uint64(len(body)), holes)
				if err != nil {
					t.Fatal(err)
				}
				var memory sparse.Source = top
				if history.base != "" {
					memory = fetch.NewLayered(&lifecycleArtifactStream{Source: top}, history.memory)
				}
				sc, err := snapshot.MarshalConfig(&snapshot.Config{Version: snapshot.SnapshotConfigVersion, SandboxRef: "manifest://" + strings.Repeat("a", 64), FromRefs: refs})
				if err != nil {
					t.Fatal(err)
				}
				source, err := snapshotfile.BuildSource(memory, []byte(fmt.Sprintf(`{"round":%d}`, round)), []byte(fmt.Sprintf(`{"cpu":%d}`, round)), sc)
				if err != nil {
					t.Fatal(err)
				}
				ref, path, err := sink.AbsorbSnapshot(ctx, source)
				if err != nil {
					t.Fatal(err)
				}
				if err := sink.CommitSnapshot(ctx, ref, path); err != nil {
					t.Fatal(err)
				}
				if err := sink.Close(); err != nil {
					t.Fatal(err)
				}
				if err := history.Close(); err != nil {
					t.Fatal(err)
				}
				if old != nil {
					if err := old.Close(); err != nil {
						t.Fatal(err)
					}
				}
				runtime := ref
				if bundleMode {
					r, _ := manifest.ParseRef(ref)
					path = filepath.Join(dir, r.Path+".bundle")
					runtime = (manifest.Ref{Scheme: manifest.RefSchemeFile, Path: path, DigestScheme: "manifest", Digest: r.Path}).String()
				} else {
					r, _ := manifest.ParseRef(ref)
					r.Path = path
					runtime = r.String()
				}
				r, _ := manifest.ParseRef(runtime)
				old, err = artifact.OpenFileWithLocations(ctx, path, r, cfg, keyFn, remote, nil, nil, false)
				if err != nil {
					t.Fatal(err)
				}
				root, err := snapshotfile.Open(ctx, old)
				if err != nil {
					t.Fatal(err)
				}
				// The next restore uses only newest S's execution state and E selection.
				if string(root.StateJSON) != fmt.Sprintf(`{"cpu":%d}`, round) {
					t.Fatalf("wrong execution tail: %s", root.StateJSON)
				}
				parsed, err := snapshot.ParseConfig(root.SnapshotConfig)
				if err != nil {
					t.Fatal(err)
				}
				localCount := len(parsed.FromRefs) - len(external)
				want := 0
				if round > 0 && !merge {
					want = 1
				}
				if localCount != want {
					t.Fatalf("round %d lower count %d, want %d: %v", round, localCount, want, parsed.FromRefs)
				}
				if !reflect.DeepEqual(parsed.FromRefs[localCount:], external) {
					t.Fatalf("external order changed: %v", parsed.FromRefs)
				}
				opts.MemoryBinding = &MemorySourceBinding{SnapshotRef: ref, RuntimeRef: runtime, RelativeDir: dir, FromRefs: parsed.FromRefs}
				if bundleMode {
					opts.MemoryBinding.BundleSource = &BundleSourceBinding{RootRef: runtime, RootPath: path, Reader: old.BundleReader(), Fetcher: old.ManifestFetcher()}
				}
				// Compare only the local prefix: external fallback is deliberately never
				// fetched while coalescing historical resident pages.
				all := prependRef(ref, parsed.FromRefs)
				prefix, err := checkpointPrefix(ctx, all, runtime, dir, opts, true)
				if err != nil {
					t.Fatal(err)
				}
				layers := []fetch.Stream{}
				for _, raw := range prefix {
					stream, err := newMemoryMergeBaseOpener(opts)(ctx, raw)
					if err != nil {
						t.Fatal(err)
					}
					layers = append(layers, stream)
				}
				merged := fetch.NewLayered(layers...)
				got := make([]byte, len(expected))
				if n, err := merged.ReadAt(ctx, got, 0); err != nil && err != io.EOF || n != len(got) {
					t.Fatalf("read memory %d: %v", n, err)
				}
				if !bytes.Equal(got, expected) {
					t.Fatalf("round %d memory composition changed", round)
				}
				if err := merged.Close(); err != nil {
					t.Fatal(err)
				}
			}
		})
	}
}

func TestCheckpointPrefixStopsAtExternalOwnership(t *testing.T) {
	dir := t.TempDir()
	external := t.TempDir()
	write := func(where string, value byte) string {
		sink := snapshot.NewFileSink(where, "sid", nil, false, nil)
		cfg, _ := snapshot.MarshalConfig(&snapshot.Config{Version: snapshot.SnapshotConfigVersion, SandboxRef: "manifest://" + strings.Repeat("a", 64)})
		ref, _, err := sink.AbsorbSnapshot(context.Background(), lifecycleSnapshotSource(t, bytes.Repeat([]byte{value}, 4096), cfg))
		if err != nil {
			t.Fatal(err)
		}
		return ref
	}
	local := write(dir, 1)
	other := write(external, 2)
	externalRef, _ := manifest.ParseRef(other)
	externalRef.Path = filepath.Join(external, externalRef.Path)
	opts := RunOptions{checkpointDir: dir}
	prefix, err := checkpointPrefix(context.Background(), []string{local, externalRef.String(), local}, "", dir, opts, true)
	if err != nil || len(prefix) != 1 {
		t.Fatalf("external path boundary: %v %v", prefix, err)
	}
	located, _ := manifest.ParseRef(local)
	located.Location = "template"
	opts.RefLocations = config.RefLocations{"template": dir}
	prefix, err = checkpointPrefix(context.Background(), []string{located.String(), local}, local, dir, opts, true)
	if err != nil || len(prefix) != 0 {
		t.Fatalf("same-path template ownership merged: %v %v", prefix, err)
	}
}

type checkpointNoFetch struct{ t *testing.T }

func (f *checkpointNoFetch) OpenManifest(context.Context, store.ContentKey) (fetch.Stream, error) {
	f.t.Error("history fetched external boundary")
	return nil, fmt.Errorf("unexpected remote open")
}

func TestCheckpointDisksMergeContiguousPrefixAndPreserveEROFS(t *testing.T) {
	ctx := context.Background()
	dir := t.TempDir()
	sink := snapshot.NewFileSink(dir, "sid", nil, false, nil)
	size := int64(4 * 4096)
	writeLayer := func(value byte, page int) string {
		body := bytes.Repeat([]byte{value}, int(size))
		holes := []sparse.Extent{}
		if page > 0 {
			holes = append(holes, sparse.Extent{Offset: 0, Size: uint64(page * 4096)})
		}
		if page < 3 {
			holes = append(holes, sparse.Extent{Offset: uint64((page + 1) * 4096), Size: uint64((3 - page) * 4096)})
		}
		ref, _, err := sink.AbsorbOverlay(ctx, bytes.NewReader(body), holes)
		if err != nil {
			t.Fatal(err)
		}
		return ref
	}
	old := writeLayer(1, 0)
	middle := writeLayer(2, 1)
	top := writeLayer(0, 0) // opaque zero replaces old data
	external := "manifest://" + strings.Repeat("e", 64)
	c0 := snapshotTestLivePortable(t)
	c0.Boot.Root.BaseFromRefs = []string{middle, old, external}
	opts := RunOptions{checkpointDir: dir, Cfg: &config.SandboxConfig{}, PortableConfig: c0,
		SourceBinding: &RunSourceBinding{SandboxRef: top, RuntimeRef: top, RelativeDir: dir}}
	views := 0
	disk := SnapDiskRef{Size: size, SnapshotView: func() (io.ReadSeeker, []sparse.Extent, error) {
		views++
		return bytes.NewReader(make([]byte, size)), nil, nil
	}}
	prepared, diffs, merged, open, err := prepareCheckpointDisks(ctx, opts, []SnapDiskRef{disk})
	if err != nil {
		t.Fatal(err)
	}
	if views != 0 {
		t.Fatal("preflight read guest writable state")
	}
	if !merged[0] || !reflect.DeepEqual(prepared.PortableConfig.Boot.Root.BaseFromRefs, []string{external}) {
		t.Fatalf("disk prefix did not converge: %v %+v", merged, prepared.PortableConfig.Boot.Root)
	}
	stream, err := open(ctx, diffs[0].MergeBase)
	if err != nil {
		t.Fatal(err)
	}
	defer stream.Close()
	got := make([]byte, size)
	if _, err := stream.ReadAt(ctx, got, 0); err != nil {
		t.Fatal(err)
	}
	want := make([]byte, size)
	copy(want[4096:8192], bytes.Repeat([]byte{2}, 4096))
	if !bytes.Equal(got, want) {
		t.Fatal("disk Data/Hole/Zero overlay differs")
	}
	run, err := stream.RunAt(8192, 4096)
	if err != nil || run.Kind() != sparse.Hole {
		t.Fatalf("disk lower fallthrough lost: %v %v", run, err)
	}
	if !reflect.DeepEqual(c0.Boot.Root.BaseFromRefs, []string{middle, old, external}) {
		t.Fatal("immutable C0 mutated")
	}
	// A direct EROFS self is not the ext4 upper's same-device parent.
	opts.PortableConfig = snapshotTestPortable(t)
	opts.PortableConfig.Boot.Root = config.PortableRootConfig{Base: "self", Overlay: &config.PortableOverlayConfig{}}
	prepared, diffs, merged, _, err = prepareCheckpointDisks(ctx, opts, []SnapDiskRef{disk})
	if err != nil || merged[0] || diffs[0].MergeBase != "" {
		t.Fatalf("EROFS merged into upper: %v %v", merged, err)
	}
	if prepared.PortableConfig.Boot.Root.Base != "self" || prepared.PortableConfig.Boot.Root.Overlay == nil {
		t.Fatal("immutable base separation changed")
	}
	// Same-path located template source remains an external owner.
	located, _ := manifest.ParseRef(top)
	located.Location = "template"
	opts.PortableConfig = c0
	opts.RefLocations = config.RefLocations{"template": dir}
	opts.SourceBinding.SandboxRef = located.String()
	_, _, merged, _, err = prepareCheckpointDisks(ctx, opts, []SnapDiskRef{disk})
	if err != nil || merged[0] {
		t.Fatalf("located disk parent absorbed: %v %v", merged, err)
	}
}

// Map failures are deliberately invisible to Snapshot's tail reader. This
// models the gap between opening S and validating its composed memory base.
type checkpointMapStream struct {
	sparse.Source
	runAt    func(uint64, uint64) (sparse.Run, error)
	maps     int
	reads    int
	closes   int
	closeErr error
}

func (s *checkpointMapStream) RunAt(offset, limit uint64) (sparse.Run, error) {
	s.maps++
	var run sparse.Run
	var err error
	if s.runAt != nil {
		run, err = s.runAt(offset, limit)
	} else {
		run, err = s.Source.RunAt(offset, limit)
	}
	if err != nil || run == nil {
		return run, err
	}
	return checkpointMapRun{Run: run, owner: s}, nil
}

type checkpointMapRun struct {
	sparse.Run
	owner *checkpointMapStream
}

func (r checkpointMapRun) ReadAt(ctx context.Context, b []byte, offset uint64) (int, error) {
	r.owner.reads++
	if r.owner.closes != 0 {
		return 0, fmt.Errorf("run read after close")
	}
	return r.Run.ReadAt(ctx, b, offset)
}

func (s *checkpointMapStream) ReadAt(ctx context.Context, b []byte, offset uint64) (int, error) {
	s.reads++
	if s.closes != 0 {
		return 0, fmt.Errorf("read after close")
	}
	return s.Source.ReadAt(ctx, b, offset)
}

func (s *checkpointMapStream) Close() error {
	s.closes++
	return s.closeErr
}

type checkpointNonprogressRun struct{ sparse.Run }

func (r checkpointNonprogressRun) End() uint64 { return r.Offset() }

func TestCheckpointMemoryMergePreflight(t *testing.T) {
	mapErr := errors.New("composed memory map failed")
	closeErr := errors.New("memory close failed")
	for _, tc := range []struct {
		name    string
		mode    string
		lower   bool
		want    error
		invalid bool
	}{
		{name: "live reader"},
		{name: "permanent top map", mode: "error", want: mapErr},
		{name: "permanent lower map", mode: "error", lower: true, want: mapErr},
		{name: "nil run", mode: "nil", invalid: true},
		{name: "nonprogressing lower run", mode: "nonprogress", lower: true, invalid: true},
		{name: "retry lower map", mode: "retry", lower: true},
		{name: "canceled before map", mode: "precancel", want: context.Canceled},
		{name: "canceled during retry", mode: "cancel", lower: true, want: context.Canceled},
		{name: "size", mode: "size", invalid: true},
	} {
		t.Run(tc.name, func(t *testing.T) {
			ctx, cancel := context.WithCancel(context.Background())
			defer cancel()
			body := bytes.Repeat([]byte{0x35}, 4096)
			stream := &checkpointMapStream{Source: sparse.Dense(bytes.NewReader(body), uint64(len(body))), closeErr: closeErr}
			stream.runAt = func(offset, limit uint64) (sparse.Run, error) {
				switch tc.mode {
				case "error":
					return nil, readerr.Mark(mapErr, false)
				case "nil":
					return nil, nil
				case "nonprogress":
					run, err := stream.Source.RunAt(offset, limit)
					return checkpointNonprogressRun{run}, err
				case "retry":
					if stream.maps == 1 {
						return nil, mapErr
					}
				case "cancel":
					cancel()
					return nil, mapErr
				}
				return stream.Source.RunAt(offset, limit)
			}
			cfg, err := snapshot.MarshalConfig(&snapshot.Config{Version: snapshot.SnapshotConfigVersion, SandboxRef: "manifest://" + strings.Repeat("a", 64)})
			if err != nil {
				t.Fatal(err)
			}
			logical, err := snapshotfile.BuildSource(stream, []byte("{}"), []byte("{}"), cfg)
			if err != nil {
				t.Fatal(err)
			}
			root, err := snapshotfile.Open(ctx, &checkpointSourceStream{Source: logical, close: stream.Close})
			if err != nil {
				t.Fatal(err)
			}
			if stream.maps != 0 || stream.reads != 0 {
				t.Fatal("opening the S tail inspected memory")
			}
			layers := []fetch.Stream{root.Memory}
			if tc.mode == "nil" || tc.mode == "nonprogress" {
				// Inject malformed runs at the composed memory boundary itself.
				// Tail sections reject these earlier as ordinary retryable errors.
				layers[0] = stream
			}
			if tc.lower {
				hole, err := sparse.NewSource(bytes.NewReader(body), uint64(len(body)), []sparse.Extent{{Size: uint64(len(body))}})
				if err != nil {
					t.Fatal(err)
				}
				layers = append([]fetch.Stream{&lifecycleArtifactStream{Source: hole}}, layers...)
			}
			h := &memoryHistory{base: "file://parent.snapshot", memory: &checkpointStream{Stream: fetch.NewLayered(layers...)}}
			if tc.mode == "precancel" {
				cancel()
			}
			size := uint64(len(body))
			if tc.mode == "size" {
				size++
			}
			err = h.validateMergeBase(ctx, size)
			if tc.want != nil {
				if !errors.Is(err, tc.want) {
					t.Fatalf("preflight = %v, want %v", err, tc.want)
				}
			} else if tc.invalid {
				if err == nil {
					t.Fatal("invalid memory map/size accepted")
				}
			} else if err != nil {
				t.Fatal(err)
			}
			if stream.reads != 0 {
				t.Fatal("preflight read memory payload")
			}
			if stream.closes != 0 {
				t.Fatal("preflight closed the borrowed memory")
			}
			if tc.mode == "precancel" && stream.maps != 0 {
				t.Fatal("map accessed after cancellation")
			}
			if tc.mode == "retry" && stream.maps != 2 {
				t.Fatalf("map attempts = %d, want 2", stream.maps)
			}
			if err == nil {
				got := make([]byte, len(body))
				if n, err := h.memory.ReadAt(ctx, got, 0); err != nil || n != len(got) || !bytes.Equal(got, body) {
					t.Fatalf("capture lost live reader: n=%d, err=%v", n, err)
				}
			}
			for i := 0; i < 2; i++ {
				if err := h.Close(); !errors.Is(err, closeErr) {
					t.Fatalf("history close = %v", err)
				}
			}
			if stream.closes != 1 {
				t.Fatalf("owner closed %d times, want once", stream.closes)
			}
		})
	}
}

type checkpointKindRun struct {
	sparse.Run
	kind sparse.RunKind
}

func (r checkpointKindRun) Kind() sparse.RunKind { return r.kind }

func TestCheckpointMemoryMergePreflightPreservesSparseKinds(t *testing.T) {
	const page = 4096
	body := bytes.Repeat([]byte{0x35}, 3*page)
	stream := &checkpointMapStream{Source: sparse.Dense(bytes.NewReader(body), uint64(len(body)))}
	kinds := []sparse.RunKind{sparse.Data, sparse.Zero, sparse.Hole}
	stream.runAt = func(offset, limit uint64) (sparse.Run, error) {
		run, err := stream.Source.RunAt(offset, min(limit, page-offset%page))
		return checkpointKindRun{Run: run, kind: kinds[offset/page]}, err
	}
	lower, err := sparse.NewSource(bytes.NewReader(body), uint64(len(body)), []sparse.Extent{{Offset: 2 * page, Size: page}})
	if err != nil {
		t.Fatal(err)
	}
	h := &memoryHistory{memory: &checkpointStream{Stream: fetch.NewLayered(stream, &lifecycleArtifactStream{Source: lower})}}
	defer h.Close()
	if err := h.validateMergeBase(context.Background(), uint64(len(body))); err != nil {
		t.Fatal(err)
	}
	if stream.maps != 3 || stream.reads != 0 || stream.closes != 0 {
		t.Fatalf("preflight maps=%d reads=%d closes=%d", stream.maps, stream.reads, stream.closes)
	}
	for i, want := range kinds {
		run, err := h.memory.RunAt(uint64(i*page), page)
		if err != nil || run.Kind() != want {
			t.Fatalf("run %d = %v, %v, want %v", i, run, err, want)
		}
	}
	got := make([]byte, len(body))
	if n, err := h.memory.ReadAt(context.Background(), got, 0); err != nil || n != len(got) {
		t.Fatalf("capture read = %d, %v", n, err)
	}
	want := make([]byte, len(body))
	copy(want[:page], body[:page])
	if !bytes.Equal(got, want) {
		t.Fatal("Data/Hole/Zero composition changed")
	}
}
